[project]
authors = ["Manish Kumar"]
entry = "main.sw"
license = "Apache-2.0"
name = "ecc"

[dependencies]
core = { git = "https://github.com/FuelLabs/sway", branch = "master" }
std = { git = "https://github.com/FuelLabs/sway", branch = "master" }
